In [1]:

from tkinter import *
import numpy as np
import pandas as pd
import os
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler


In [2]:
#List of the symptoms is listed here in list l1.

l1=['itching','skin_rash','nodal_skin_eruptions','continuous_sneezing','shivering','chills','joint_pain',
    'stomach_pain','acidity','ulcers_on_tongue','muscle_wasting','vomiting','burning_micturition','spotting_urination','fatigue',
    'weight_gain','anxiety','mood_swings','weight_loss','restlessness','lethargy','patches_in_throat',
    'irregular_sugar_level','cough','high_fever','sunken_eyes','breathlessness','sweating','dehydration','indigestion',
    'headache','yellowish_skin','dark_urine','nausea','loss_of_appetite','pain_behind_the_eyes','back_pain','constipation',
    'abdominal_pain','diarrhoea','mild_fever','yellow_urine','yellowing_of_eyes','acute_liver_failure','fluid_overload',
    'swelling_of_stomach','swelled_lymph_nodes','malaise','blurred_and_distorted_vision','phlegm','throat_irritation',
    'redness_of_eyes','sinus_pressure','runny_nose','congestion','chest_pain','weakness_in_limbs','fast_heart_rate',
    'pain_during_bowel_movements','pain_in_anal_region','bloody_stool','irritation_in_anus','neck_pain','dizziness','cramps',
    'bruising','obesity','swollen_legs','swollen_blood_vessels','puffy_face_and_eyes','enlarged_thyroid','brittle_nails',
    'swollen_extremities','excessive_hunger','extra_marital_contacts','drying_and_tingling_lips','slurred_speech','knee_pain','hip_joint_pain',
    'muscle_weakness','stiff_neck','swelling_joints','movement_stiffness','spinning_movements','loss_of_balance','unsteadiness','weakness_of_one_body_side',
    'loss_of_smell','bladder_discomfort','foul_smell_of urine','continuous_feel_of_urine','passage_of_gases','internal_itching','toxic_look_(typhus)',
    'depression','irritability','muscle_pain','altered_sensorium','red_spots_over_body','belly_pain','abnormal_menstruation',
    'watering_from_eyes','increased_appetite','polyuria','family_history','mucoid_sputum','rusty_sputum','lack_of_concentration','visual_disturbances',
    'receiving_blood_transfusion','receiving_unsterile_injections','coma','stomach_bleeding','distention_of_abdomen','history_of_alcohol_consumption',
    'fluid_overload','blood_in_sputum','prominent_veins_on_calf','palpitations','painful_walking','pus_filled_pimples','blackheads','scurrying','skin_peeling',
    'silver_like_dusting','small_dents_in_nails','inflammatory_nails','blister','red_sore_around_nose','yellow_crust_ooze']

In [3]:
#List of Diseases is listed in list disease.
disease=['Fungal infection','Allergy','GERD','Chronic cholestasis','Drug Reaction',
        'Peptic ulcer diseae','AIDS','Diabetes','Gastroenteritis','Bronchial Asthma','Hypertension',
        ' Migraine','Cervical spondylosis',
        'Paralysis (brain hemorrhage)','Jaundice','Malaria','Chicken pox','Dengue','Typhoid','hepatitis A',
'Hepatitis B','Hepatitis C','Hepatitis D','Hepatitis E','Alcoholic hepatitis','Tuberculosis',
'Common Cold','Pneumonia','Dimorphic hemmorhoids(piles)',
'Heartattack','Varicoseveins','Hypothyroidism','Hyperthyroidism','Hypoglycemia','Osteoarthristis',
'Arthritis','(vertigo) Paroymsal  Positional Vertigo','Acne','Urinary tract infection','Psoriasis',
'Impetigo']

In [4]:
l2=[]
for i in range(0,len(l1)):
    l2.append(0)
print(l2)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [5]:
#Reading the training .csv file
df=pd.read_csv(r'C:\Users\huzai\vs code projects\Disease-Prediction\dataset\Training.csv')
DF= pd.read_csv(r'C:\Users\huzai\vs code projects\Disease-Prediction\dataset\Training.csv', index_col='prognosis')
#Replace the values in the imported file by pandas by the inbuilt function replace in pandas.

df.replace({'prognosis':{'Fungal infection':0,'Allergy':1,'GERD':2,'Chronic cholestasis':3,'Drug Reaction':4,
    'Peptic ulcer diseae':5,'AIDS':6,'Diabetes ':7,'Gastroenteritis':8,'Bronchial Asthma':9,'Hypertension ':10,
    'Migraine':11,'Cervical spondylosis':12,
    'Paralysis (brain hemorrhage)':13,'Jaundice':14,'Malaria':15,'Chicken pox':16,'Dengue':17,'Typhoid':18,'hepatitis A':19,
    'Hepatitis B':20,'Hepatitis C':21,'Hepatitis D':22,'Hepatitis E':23,'Alcoholic hepatitis':24,'Tuberculosis':25,
    'Common Cold':26,'Pneumonia':27,'Dimorphic hemmorhoids(piles)':28,'Heart attack':29,'Varicose veins':30,'Hypothyroidism':31,
    'Hyperthyroidism':32,'Hypoglycemia':33,'Osteoarthristis':34,'Arthritis':35,
    '(vertigo) Paroymsal  Positional Vertigo':36,'Acne':37,'Urinary tract infection':38,'Psoriasis':39,
    'Impetigo':40}},inplace=True)
df.head(100)

abdominal_pain  abnormal_menstruation  acidity  acute_liver_failure  \
0                0                      0        0                    0   
1                0                      0        0                    0   
2                0                      0        0                    0   
3                0                      0        0                    0   
4                0                      0        0                    0   
..             ...                    ...      ...                  ...   
95               0                      0        0                    0   
96               0                      0        0                    0   
97               0                      0        0                    0   
98               0                      0        0                    0   
99               0                      0        0                    0   

    altered_sensorium  anxiety  back_pain  belly_pain  blackheads  \
0                   0        0          0           0           0   
1                   0        0          0           0           0   
2                   0        0          0           0           0   
3                   0        0          0           0           0   
4                   0        0          0           0           0   
..                ...      ...        ...         ...         ...   
95                  0        0          0           0           0   
96                  0        0          0           0           0   
97                  0        0          0           0           0   
98                  0        0          0           0           0   
99                  0        0          0           0           0   

    bladder_discomfort  ...  watering_from_eyes  weakness_in_limbs  \
0                    0  ...                   0                  0   
1                    0  ...                   0                  0   
2                    0  ...                   0                  0   
3                    0  ...                   0                  0   
4                    0  ...                   0                  0   
..                 ...  ...                 ...                ...   
95                   0  ...                   0                  0   
96                   0  ...                   0                  0   
97                   0  ...                   0                  0   
98                   0  ...                   0                  0   
99                   0  ...                   0                  0   

    weakness_of_one_body_side  weight_gain  weight_loss  yellow_crust_ooze  \
0                           0            0            0                  0   
1                           0            0            0                  0   
2                           0            0            0                  0   
3                           0            0            0                  0   
4                           0            0            0                  0   
..                        ...          ...          ...                ...   
95                          0            0            0                  0   
96                          0            0            0                  0   
97                          0            0            0                  0   
98                          0            0            0                  0   
99                          0            0            0                  0   

    yellow_urine  yellowing_of_eyes  yellowish_skin  \
0              0                  0               0   
1              0                  0               0   
2              0                  0               0   
3              0                  0               0   
4              0                  0               0   
..           ...                ...             ...   
95             0                  0               0   
96             0                  0               0   
9

In [6]:
X= df[l1]
y = df[["prognosis"]]
y = np.ravel(y)


In [7]:
y

array([6, 6, 6, 6, 6, 37, 37, 37, 37, 37, 24, 24, 24, 24, 24, 24, 24, 24,
       1, 1, 1, 1, 1, 35, 35, 35, 35, 35, 35, 9, 9, 9, 9, 9, 9, 9, 12, 12,
       12, 12, 12, 12, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 3, 3, 3, 3,
       3, 3, 3, 3, 26, 26, 26, 26, 26, 26, 26, 26, 26, 'Covid', 'Covid',
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       'Dimorphic hemorrhoids(piles)', 'Dimorphic hemorrhoids(piles)',
       'Dimorphic hemorrhoids(piles)', 'Dimorphic hemorrhoids(piles)',
       'Dimorphic hemorrhoids(piles)', 'Dimorphic hemorrhoids(piles)', 4,
       4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 8, 8, 8, 8, 8,
       29, 29, 29, 29, 29, 'Hepatitis A', 'Hepatitis A', 'Hepatitis A',
       'Hepatitis A', 'Hepatitis A', 'Hepatitis A', 'Hepatitis A',
       'Hepatitis A', 'Hepatitis A', 20, 20, 20, 20, 20, 20, 20, 20, 20,
       21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
       23, 23, 23, 23, 23, 23, 23, 23, 23, 10, 10, 10

In [8]:
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder object
label_encoder = LabelEncoder()

# Fit and transform the target variable
y_encoded = label_encoder.fit_transform(y)

TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['int', 'str']

In [ ]:
unique_values = df['prognosis'].unique()

# To display the unique values
print(unique_values)


[6 37 24 1 35 9 12 16 3 26 'Covid' 17 7 'Dimorphic hemorrhoids(piles)' 4 0
 2 8 29 'Hepatitis A' 20 21 22 23 10 32 33 31 40 14 15 11 'Osteoarthritis'
 13 'Paralysis (brain hemorrhageH' 'Paroxysmal Positional Vertigo'
 'Peptic ulcer disease' 27 39 25 18 38 30]


In [ ]:
y = pd.to_numeric(y, errors='coerce')

In [ ]:
y

array([ 6.        ,  6.        ,  6.        ,  6.        ,  6.        ,
       37.        , 37.        , 37.        , 37.        , 37.        ,
       24.        , 24.        , 24.        , 24.        , 24.        ,
       24.        , 24.        , 24.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        , 35.        , 35.        ,
       35.        , 35.        , 35.        , 35.        ,  9.        ,
        9.        ,  9.        ,  9.        ,  9.        ,  9.        ,
        9.        , 12.        , 12.        , 12.        , 12.        ,
       12.        , 12.        , 16.        , 16.        , 16.        ,
       16.        , 16.        , 16.        , 16.        , 16.        ,
       16.        , 16.        ,  3.        ,  3.        ,  3.        ,
        3.        ,  3.        ,  3.        ,  3.        ,  3.        ,
       26.        , 26.        , 26.        , 26.        , 26.        ,
       26.        , 26.        , 26.        , 26.        , 19.69

In [ ]:
print(y[:10])  # Look at the first few elements to confirm data type
print(y.dtype) # Confirm it is integer or category, not float

[ 6.  6.  6.  6.  6. 37. 37. 37. 37. 37.]
float64


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)

knn=knn.fit(X,np.ravel(y))

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [ ]:
import pickle

knnPickle1 = open('Symptom', 'wb') 
pickle.dump(knn, knnPickle1)
knnPickle1.close()